
# parsetab.py
# This file is automatically generated. Do not edit.

_lr_method = 'SLR'

_lr_signature = '\xd4p\x02\xe6^\xeb\x1b\xa7\xf4\r\xb2\xf7!\xf32\x1d'

_lr_action_items = {'AND':([13,1,6,2,15,17,16,14,3,5,4,],[11,-11,-5,-8,-7,-4,-3,-6,-10,11,-9,]),'QUOTEDVALUE':([8,10,12,0,9,11,],[1,1,1,1,1,1,]),'ATTR':([12,0,8,11,],[2,2,2,2,]),'CLASS':([0,],[8,]),'NEQ':([2,],[10,]),'EQ':([2,],[9,]),'OR':([1,15,13,6,4,2,14,5,17,16,3,],[-11,-7,12,-5,-9,-8,-6,12,-4,-3,-10,]),'VALUE':([11,9,12,10,8,0,],[3,3,3,3,3,3,]),'$':([17,14,2,5,3,7,13,16,15,1,4,6,],[-4,-6,-8,-2,-10,0,-1,-3,-7,-11,-9,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_action[(_x,_k)] = _y
del _lr_action_items

_lr_goto_items = {'querystr':([0,11,12,8,],[6,16,17,6,]),'total':([0,],[7,]),'value':([12,11,10,8,9,0,],[4,4,15,4,14,4,]),'query':([8,0,],[13,5,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       _lr_goto[(_x,_k)] = _y
del _lr_goto_items
_lr_productions = [
  ("S'",1,None,None,None),
  ('total',2,'p_total_class_query','QueryParser.py',74),
  ('total',1,'p_total_query','QueryParser.py',80),
  ('query',3,'p_query_oper_querystr','QueryParser.py',86),
  ('query',3,'p_query_oper_querystr','QueryParser.py',87),
  ('query',1,'p_query_querystr','QueryParser.py',97),
  ('querystr',3,'p_querystr_attr_value','QueryParser.py',104),
  ('querystr',3,'p_querystr_attr_value','QueryParser.py',105),
  ('querystr',1,'p_querystr_attr','QueryParser.py',110),
  ('querystr',1,'p_querystr_value','QueryParser.py',115),
  ('value',1,'p_value','QueryParser.py',121),
  ('value',1,'p_quotedvalue','QueryParser.py',128),
]
